[profile.default]
optimizer = true
optimizer_runs = 200
contracts = "contracts"
fuzz_max_global_rejects = 100000
fuzz_max_local_rejects = 100000
fuzz_runs = 500
libs = ['node_modules', 'lib', 'contracts/test', 'contracts/mock', 'forge-std/lib/ds-test/src', 'forge-std/src']
